# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='', upload_to='pdfs'),
        ),
    ]
